In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(np.transpose(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
A=np.array([[1,2,3],
           [6,5,4],
           [9,7,8]])
B=np.array([[0,1,2],
           [3,4,5],
           [6,7,8]])
print(A)
print(B)

[[1 2 3]
 [6 5 4]
 [9 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
print(np.matmul(A,B))

[[ 24  30  36]
 [ 39  54  69]
 [ 69  93 117]]
